name: Feature branch

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - develop

env:
  NODE_VERSION: '20'
  MONGODB_VERSION: '7.0'

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}
          mongodb-replica-set: rs0

      # Main logic
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile

      - name: Code checking
        run: |
          yarn generate
          yarn lint
          yarn ts-check

      - name: Jest unit tests
        # add following to `yarn test`:
        #  --forceExit to bypass --detectOpenHandle error
        run: |
          yarn jest --ci --runInBand --env=node

      - name: Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start:cypress
          wait-on: 'http://localhost:3000'
          command: yarn cy:run
          record: false
          parallel: false

      # After the test run completes, store videos and any screenshots
      - name: Cypress upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          retention-days: 5
          path: |
            cypress/screenshots
            cypress/videos
