name: Main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      # needed to create tags and GitHub releases
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # needed to fetch all tags for version detection

      - name: Enable corepack to support yarn@4
        run: corepack enable

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install release tools
        run: |
           yarn add release-it @release-it/conventional-changelog
           # discard changes to yarn.lock, so working directory is clean
           git checkout -- .
           git config --global user.name "github-actions[bot]"
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create release
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Azure deployment uses up way too much github action minutes
  # deploy:
  #   name: Deploy to Azure
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@master

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: 'Deploy to Azure WebApp'
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         slot-name: production
